Application:

  type: "BackTesting"

  clockId: "Simulation"

  dataStoreId: "InMemory"
  persistenceMode: "Disable"
  createDBAtStart : false
  deleteDBAtStop : false

  feedId: "CSV"
  brokerId: "Simulator"
  portfolioId: "test"
  stgId: "down2%"
  stgCls: "algotrader.strategy.down_2pct_strategy.Down2PctStrategy"
  instrumentIds:
    - "SPY@NYSEARCA"
  subscriptionTypes:
    - "Bar.Yahoo.Time.D1"
  subscriptions:
  fromDate : 20100101
  toDate :
  portfolioInitialcash : 100000


Strategy:
  down2%:
    qty: 1


DataStore:

  Cassandra:
    contactPoints:
      - "127.0.0.1"
    port:
    username:
    password:
    keyspace: "algotrader"
    scriptPath: "../../../scripts/cassandra/algotrader.cql"

  Mongo:
    host: "localhost"
    port: 27107
    username:
    password:
    dbname: "algotrader"

  InMemory:
    file: "algotrader_db.p"

Feed:
  CSV:
    path: "../data/tradedata"

Broker:
  IB:
    host: "localhost"
    port: 4001
    clientId: 0
    account: 1
    daemon: true
    useGevent: false
    nextRequestId: 1
    nextOrderId: 1

  Simulator:
    commission: "Default"
    fillStrategy: "Default"
    nextOrderId: 1
    nextExecId: 1
