Application:

  type: "DataImport"

  clockId: "RealTime"

  dataStoreId: "Mongo"
  persistenceMode: "RealTime"
  createDBAtStart : false
  deleteDBAtStop : false

  fromDate : 20100101
  toDate : 20170101


DataStore:

  Cassandra:
    contactPoints:
      - "127.0.0.1"
    port:
    username:
    password:
    keyspace: "algotrader"
    scriptPath: "../../../scripts/cassandra/algotrader.cql"

  Mongo:
    host: "localhost"
    port: 27017
    username:
    password:
    dbname: "algotrader"

  InMemory:
    file: "algotrader_db.p"

Feed:
  CSV:
    path: "../data/tradedata"
