Application:
  stgId: "down2%"
  stgCls: "algotrader.strategy.down_2pct_strategy.Down2PctStrategy"
  instrumentIds:
    - "SPY@NYSEARCA"
  subscriptionTypes:
    - "Bar.Yahoo.Time.D1"
  subscriptions:

Strategy:
  down2%:
    qty: 1
